### ISSUE TITLE
Can't use it with @radix-ui/themes

### ISSUE THREAD

**Issue by nemanjam** [abhijithvijayan/web-extension-starter#102]
In `Popup.tsx` when I import this:

```tsx
import '@radix-ui/themes/styles.css';
```
I get this postcss related error log:

```
[webpack-cli] JisonParserError: Parse error on line 1: 
...m-start)) - var(--line-height, calc(1em * var(--default-line-height))) / 2
------------------------------------------------------------------------^
Expecting end of input, "ADD", "SUB", "MUL", "DIV", got unexpected "RPAREN"
    at /home/username/Desktop/reddit-unread-comments/css/popup.css:15963:5
    at Parser.parseError (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/dist/parser.js:1200:15)
    at Parser.parse (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/dist/parser.js:1716:30)
    at /home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at _default (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/dist/lib/transform.js:66:100)
    at callback (/home/username/Desktop/reddit-unread-comments/node_modules/postcss-calc/dist/index.js:27:32)
...
```
This doesn't fix it:

https://github.com/postcss/postcss-calc/issues/77#issuecomment-491354918

https://github.com/radix-ui/themes/issues/104

**Comment by nemanjam** [comment]
Updating this package fixes it:

```json
"optimize-css-assets-webpack-plugin": "^6.0.1",
```
